n= int(input("So tien ban dau:"))
k= int(input("So thang gui:"))
T= float(input("Lai suat/ thang:"))
print("Voi so tien ban dau",n,",sau",k,"thang gui, lai suat",T,"/thang")
print("Thi tong so tien nhan duoc cuoi ky la:",n*(1+k*T))